### ISSUE TITLE
VOC2012_seg_img.npy

### ISSUE THREAD

**Issue by SSUHan** [cvlab-yonsei/projects#1]
Hello, 
I want to execute your code for train-phrase, but I get this error:

```
FileNotFoundError: [Errno 2] No such file or directory: './data/VOC2012_seg_img.npy'
```
Where can I get this file? 

Thank you :)

**Comment by junghyup-lee** [comment]
Please refer to the README file in the '/projects/SFNet/codes/' folder.
Sorry for the confusion. We will create a separate repository for the codes soon.
