### ISSUE TITLE
I have questions about SFNet.

### ISSUE THREAD

**Issue by UdonDa** [cvlab-yonsei/projects#4]
Thank you for sharing nice implementations!

I have questions about SFNet.

First, do you have the plan to provide the evaluation code of Caltech101?
Second, how did you make the corresponding map like Fig3 in the paper?

Thanks.

**Comment by Shape-Kim** [comment]
Sorry for the late reply.

First, we do not plan to provide Caltech-101 evaluation code yet.
Second, we've written the source code ourselves to visualize the alignment results in Fig. 3, which leverages the cv2 library. If you need a reference code, please visit the [Ignacio Rocco](https://github.com/ignacio-rocco/weakalign) website. It will help you.

Thank you for your attention!
