### ISSUE TITLE
quertion about the GCP

### ISSUE THREAD

**Issue by ycy-upup** [cvlab-yonsei/projects#5]
I want to know the computation of contrastive feature. 
Pcontrast = 1*Pavg-1*Pmax
or
Pcontrast = 1*Pavg-1/6*Pmax
or
Pcontrast = 6*Pavg-1*Pmax

**Comment by hyunjp** [comment]
Thanks for your attention to our work and sorry for the very late answer.

Pcontrast = 6Pavg-1Pmax

which means the rest features against from Pmax.
