### ISSUE TITLE
Question about code?

### ISSUE THREAD

**Issue by xuzhongyou** [cvlab-yonsei/projects#6]
![image](https://user-images.githubusercontent.com/16487416/74123844-07f3f080-4c0b-11ea-9579-089e3557b77b.png)
What's the reason about 'corr_T2S = corr_feat3 * corr_feat4', and where can found the explanation in the paper?

**Comment by junghyup-lee** [comment]
Thank you for your interest in our work.
It combines the correlation maps obtained by two different feature map pairs (conv4-23 and conv5-3).
Please refer to the Sec.4.1 and Sec4.4 in our CVPR paper for details.

**Comment by GuaPiQ** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/16487416/74123844-07f3f080-4c0b-11ea-9579-089e3557b77b.png)
> What's the reason about 'corr_T2S = corr_feat3 * corr_feat4', and where can found the explanation in the paper?
Hi,  Can you send me a copy if it's convenient? My email: fengfang0901@163.com  thank you very much

**Comment by GuaPiQ** [comment]
Hi, Can you send me a copy if it's convenient? My email: fengfang0901@163.com thank you very much

**Comment by GuaPiQ** [comment]
Hello,  would you send me the code of Relation Network for Person Re-identiﬁcation if it is convenient?
my mail box：fengfang0901@163.com  Thank you very much

**Comment by hyunjp** [comment]
Hi.
We just uploaded the codes for "Relation Network for Person Re-identification".
Contact me if you have any questions about the codes.
