### ISSUE TITLE
Question about the experiment result

### ISSUE THREAD

**Issue by peterzpy** [cvlab-yonsei/projects#7]
Hello, do you use re-ranking or some tricks in your experiment? I can't reproduce the metric by using the config in your paper. In Market1501 dataset, I just got a 0.75 mAP with GCP and one-vs.-rest module. Expected for your reply, thank you.

**Comment by hyunjp** [comment]
Hi
We did not use re-ranking.
Our codes and the pre-trained weights are uploaded.
You can see the below picture if you implement our codes with the pre-trained weights.
![image](https://user-images.githubusercontent.com/29619768/77858669-c7464a00-723f-11ea-80bb-a1e94828b8e5.png)
Note that, two GPUs are needed to implement the model with our pre-trained weights.

**Comment by peterzpy** [comment]
Thanks for your reply，I will go to try this code.  : )
